# Generated by Django 6.0.3 on 2026-04-06 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='projects_workspa_658984_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'slug'), name='uq_project_workspace_slug')],
            },
        ),
    ]
