# Generated by Django 6.0.3 on 2026-04-13 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assignee_changed', 'Assignee Changed'), ('due_date_changed', 'Due Date Changed')], max_length=20)),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='New Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Task History',
                'db_table': 'task_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_assigne_972e70_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reporter'], name='tasks_reporte_f87a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['task', '-created_at'], name='task_histor_task_id_bd5439_idx'),
        ),
    ]
