# Generated by Django 6.0.3 on 2026-04-06 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Workspace Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Creator & primary admin. Multi-user access handled via Membership (Phase 3.3).', on_delete=django.db.models.deletion.RESTRICT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='workspaces_owner_i_a912d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uq_workspace_slug')],
            },
        ),
    ]
